main: me.k37.healthy.Main
name: Healthy
version: v2.0.0-alpha
author: k37
api-version: 1.16

commands:
  hearts:
    description: Sets user/player's hearts
    usage: /<command> [player] [amount] or /<command> [amount]
    aliases: ht
  foodpoints:
    description: Sets user/player's food points 
    usage: /<command> [player] [amount] or /command [amount]
    aliases: fp
  saturation:
    description: Sets user/player's saturation
    usage: /<command> [player] [amount] or /<command> [amount]
    aliases: sat
  potion:
    description: Set Potion
    usage: /<command> [amount]
    aliases: pot